### PR TITLE
Added logo to readme

### PR DESCRIPTION
**Pull request by Viz38**
I'm not sure if the logo thing actually works :man_facepalming:

### CODE REVIEW

**Comment by elmentrix** [comment]
> I'm not sure if the logo thing actually works man_facepalming

I guess we don't need a logo at the movement!, also does the path of logo is proper?

**Comment by Viz38** [comment]
> > I'm not sure if the logo thing actually works man_facepalming
> 
> I guess we don't need a logo at the movement!, also does the path of logo is proper?

Yup, I've added the jpg file

**Comment by nikhil-amin** [comment]
> > > I'm not sure if the logo thing actually works man_facepalming
> > 
> > 
> > I guess we don't need a logo at the movement!, also does the path of logo is proper?
> 
> Yup, I've added the jpg file

This will work ✌️ 
`GlugPace Logo`

**Comment by Viz38** [comment]
> > > > I'm not sure if the logo thing actually works man_facepalming
> > > 
> > > 
> > > I guess we don't need a logo at the movement!, also does the path of logo is proper?
> > 
> > 
> > Yup, I've added the jpg file
> 
> This will work ✌️
> `GlugPace Logo`

So shall I push it in?

**Comment by nikhil-amin** [comment]
> > > > > I'm not sure if the logo thing actually works man_facepalming
> > > > 
> > > > 
> > > > I guess we don't need a logo at the movement!, also does the path of logo is proper?
> > > 
> > > 
> > > Yup, I've added the jpg file
> > 
> > 
> > This will work ✌️
> > `GlugPace Logo`
> 
> So shall I push it in?

Yes, Go on buddy!

**Pull request merged**
